name: Java CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build and Publish with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          KUBEJS_DOCS_TOKEN: ${{ secrets.KUBEJS_DOCS_TOKEN }}
        with:
          arguments: run --stacktrace --no-daemon
      - name: Release to CurseForge
        uses: gradle/gradle-build-action@v2
        if: |
          contains(github.ref, 'main') && !contains(github.event.head_commit.message, '[norelease]') && github.event.inputs.norelease != 'true'
        env:
          GIT_COMMIT: ${{ github.event.after }}